#!/usr/bin/env python3
"""
Python bridge script to process exam PDFs using the Exam-Marker3 backend.
This script is generated by the web application and serves as a bridge between
the Next.js frontend and the Python backend.
"""
import os
import sys
import shutil
import asyncio
import json
from pathlib import Path

# Add the Exam-Marker3 source directory to the Python path
exam_marker_path = "/home/ubuntu/project/Exam-Marker3"
sys.path.append(os.path.join(exam_marker_path, "src"))

# Import the exam_marker package
try:
    from exam_marker.marker import ExamMarker
    import google.generativeai as genai
except ImportError as e:
    print(f"Error importing required packages: {e}")
    print("Please ensure the Exam-Marker3 repository is properly installed.")
    sys.exit(1)

async def process_pdfs(pdf_dir, output_dir, env_file):
    """Process all PDFs in the given directory using the Exam-Marker3 backend."""
    # Load environment variables from the provided .env file
    env_vars = {}
    with open(env_file, 'r') as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith('#'):
                key, value = line.split('=', 1)
                env_vars[key] = value
                os.environ[key] = value
    
    # Configure Gemini API
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        print("Error: GEMINI_API_KEY not found in .env file")
        return {"error": "GEMINI_API_KEY not found in .env file"}
    
    genai.configure(api_key=api_key)
    generation_config = {
        "temperature": 0.1,
        "top_p": 0.95,
        "top_k": 40,
        "max_output_tokens": 8192,
        "response_mime_type": "text/plain",
    }
    model = genai.GenerativeModel(
        model_name="gemini-2.0-flash-exp",
        generation_config=generation_config,
    )
    
    # Initialize marker
    marker = ExamMarker(model=model, marker_name="Web Application", gemini_api_key=api_key)
    
    # Process all PDFs in directory
    pdf_files = sorted(Path(pdf_dir).glob("*.pdf"))
    if not pdf_files:
        return {"error": f"No PDF files found in {pdf_dir}"}
    
    print(f"Found {len(pdf_files)} exam PDFs to process")
    results = []
    
    for i, pdf_path in enumerate(pdf_files, 1):
        print(f"Processing exam {i}/{len(pdf_files)}: {pdf_path.name}")
        
        try:
            # Process PDF
            feedback = await marker.process_pdf(str(pdf_path))
            
            # Save individual feedback
            output_path = Path(output_dir) / f"{pdf_path.stem}_feedback.md"
            output_path.write_text(feedback)
            print(f"Saved feedback to {output_path}")
            
            # Add to results
            results.append({
                "filename": pdf_path.name,
                "output_file": output_path.name,
                "status": "success"
            })
            
        except Exception as e:
            error_msg = f"Error processing {pdf_path.name}: {str(e)}"
            print(error_msg)
            results.append({
                "filename": pdf_path.name,
                "error": error_msg,
                "status": "error"
            })
    
    # Save combined feedback
    all_feedback = []
    for pdf_path in pdf_files:
        output_path = Path(output_dir) / f"{pdf_path.stem}_feedback.md"
        if output_path.exists():
            feedback = output_path.read_text()
            all_feedback.append(feedback)
            all_feedback.append("\n---\n")
    
    combined_path = Path(output_dir) / "all_exam_feedback.md"
    combined_feedback = "\n".join(all_feedback)
    combined_path.write_text(combined_feedback)
    
    return {
        "total_exams": len(pdf_files),
        "successful": sum(1 for r in results if r["status"] == "success"),
        "failed": sum(1 for r in results if r["status"] == "error"),
        "results": results,
        "combined_feedback": str(combined_path)
    }

if __name__ == "__main__":
    # Get command line arguments
    if len(sys.argv) != 4:
        print("Usage: process_exams.py <pdf_dir> <output_dir> <env_file>")
        sys.exit(1)
    
    pdf_dir = sys.argv[1]
    output_dir = sys.argv[2]
    env_file = sys.argv[3]
    
    # Ensure output directory exists
    os.makedirs(output_dir, exist_ok=True)
    
    # Process PDFs
    result = asyncio.run(process_pdfs(pdf_dir, output_dir, env_file))
    
    # Output results as JSON
    print(json.dumps(result))
